### ISSUE TITLE
Case Study 2 Issue

### ISSUE THREAD

**Issue by Spencer-Garcia** [BYUI335/M335_SP20_Ferrin_Brit#1]
Brittany your plots looked good. Second plot you just need to adjust the black points in relation to the population

**Comment by vanman247** [comment]
Over all good, you know Rstudio very well, your code is clean and clear of bugs, like mentioned by @Spencer-Garcia , and @dkpalmers, there just needs to be an adjustment of the size of the population , try using the ( ie: avePop <- pop/100000)

**Comment by ferrin8** [comment]
I fixed the problem. Thank you!
