### ISSUE TITLE
Graphic 1

### ISSUE THREAD

**Issue by Sdobbs3166** [BYUI335/M335_SP20_Ferrin_Brit#2]
I would consider doing something different to highlight what you want the user to see in the first graphic. I personally have a hard time seeing a difference between some of the more dense violin areas.

**Comment by ferrin8** [comment]
As stated in the preceding paragraph in the analysis, that first graph is just to show how complex the data is. I think the violin graphs do a good job at showing how the data can really vary from airport to airport, and how many outliers we're dealing with.
