### ISSUE TITLE
Case Study 10

### ISSUE THREAD

**Issue by eliseps** [BYUI335/M335_SP20_Ferrin_Brit#4]
In your MD file, your graph is not showing up. On your dygraph that we looked at in class, I can't see if you adjusted it or not yet, but you can easily adjust your legend so that it only displays when you hover over the graph with "dyLegend(show = "onmouseover")" being piped in at the end of your dyGraph function.
Also, there is quite a bit of code being displayed that is not necessary, you mentioned it in class but it's still there just to let you know.
Aside from those small things, your analysis looks great!

**Comment by ferrin8** [comment]
I have the shiny link posted and fixed that legend issue. Thank you for your help!
